ALTER TABLE grants ADD COLUMN branch_id TEXT NOT NULL DEFAULT 'branch.legacy-unbound';
ALTER TABLE grants ADD COLUMN object_scopes_json TEXT NOT NULL DEFAULT '[]';
ALTER TABLE grants ADD COLUMN budget_json TEXT NOT NULL DEFAULT '{}';
ALTER TABLE grants ADD COLUMN usage_json TEXT NOT NULL DEFAULT '{}';
ALTER TABLE grants ADD COLUMN status TEXT NOT NULL DEFAULT 'LEGACY_UNBOUND'
  CHECK (status IN ('ACTIVE', 'REVOKED', 'EXPIRED', 'LEGACY_UNBOUND'));

