export { COMMAND_DEFINITIONS, KNOWN_GRANT_SCOPES, getCommandDefinition, listCommandDefinitions } from './command-catalog.js';
export {
  ATLAS_PROCESSOR_ID,
  MAX_ATLAS_INPUT_BYTES,
  MAX_ATLAS_OUTPUT_BYTES,
  MAX_ATLAS_JOB_ATTEMPTS,
  MAX_ATLAS_OUTPUT_PIXELS,
  MAX_ATLAS_RECTANGLES,
  MAX_ATLAS_SOURCE_DIMENSION,
  TRANSPARENT_PADDING_POLICY,
  canonicalRgbaPngByteSize,
  proposeRegularGrid,
  validateAtlasRectangles,
} from './atlas-definition.js';
export {
  EXACT_PNG_CROP_OPERATION_KIND,
  PROCESSING_RECIPE_KIND,
  PROCESSING_RECIPE_OPERATION_KINDS,
  PROCESSING_RECIPE_SCHEMA_VERSION,
  canonicalProcessingRecipeJson,
  createExactPngCropProcessingRecipe,
  processingRecipeSha256,
  validateProcessingRecipe,
} from './processing-recipe.js';
export {
  MAX_PROCESSING_RESULT_FINDINGS,
  PROCESSING_RESULT_KIND,
  PROCESSING_RESULT_SCHEMA_VERSION,
  PROCESSING_RESULT_SEVERITIES,
  canonicalProcessingResultJson,
  processingResultSha256,
  validateProcessingResult,
  validateProcessingResultForRecipe,
} from './processing-result.js';
export {
  ASSET_INPUT_SELECTION_ASSET_KINDS,
  ASSET_INPUT_SELECTION_KIND,
  ASSET_INPUT_SELECTION_SCHEMA_VERSION,
  PRIMARY_VISUAL_ASSET_INPUT_ROLE,
  assetInputSelectionSha256,
  canonicalAssetInputSelectionJson,
  createPrimaryVisualAssetInputSelection,
  validateAssetInputSelection,
  validateAssetInputSelectionForProcessingResult,
} from './asset-input-selection.js';
export {
  ASSET_KINDS,
  ASSET_LIFECYCLES,
  ASSET_VALIDATOR_VERSION,
  MAX_ASSET_PROPOSAL_ITEMS,
  evaluateAssetLifecycle,
  validateAssetMetadata,
  validateAssetProposal,
  validateExactSliceBinding,
  validateSurfaceTilingDomain,
} from './asset-definition.js';
export {
  MAX_ROOM_ARCHETYPES,
  MAX_ROOM_AXIS_CELLS,
  MAX_ROOM_CELLS,
  MAX_ROOM_CONNECTORS,
  MAX_ROOM_INTENT_REFS,
  MAX_ROOM_PLACEMENTS,
  MAX_ROOM_PROPOSAL_ITEMS,
  MAX_ROOM_VARIANTS,
  ROOM_KINDS,
  ROOM_LAYERS,
  ROOM_LIFECYCLES,
  ROOM_ROTATIONS,
  ROOM_VALIDATOR_VERSION,
  evaluateRoomLifecycle,
  forkFinalRoomVariant,
  roomArchetypeDefaults,
  validateRoomArchetype,
  validateRoomPlacementProposal,
  validateRoomVariant,
} from './room-definition.js';
export {
  AGENT_TASK_STATES,
  REVIEW_DISPOSITIONS,
  applyReviewDecisions,
  assertReviewMergeable,
  assertTaskCanExecute,
  createReviewItems,
  findSemanticConflicts,
  semanticChangeKey,
  transitionAgentTask,
  validateAgentTaskSpec,
} from './agent-task.js';
export {
  PROJECT_CAPABILITY_MANIFEST_KIND,
  PROJECT_CAPABILITY_MANIFEST_SCHEMA_VERSION,
  PROJECT_CAPABILITY_OPERATION_KINDS,
  PROJECT_CAPABILITY_VOCABULARY_FIELDS,
  canonicalProjectCapabilityManifestJson,
  projectCapabilityManifestSha256,
  validateProjectCapabilityManifest,
} from './project-capability-manifest.js';
export {
  CANDIDATE_COMPILER_STATUSES,
  CANDIDATE_MANIFEST_KIND,
  CANDIDATE_MANIFEST_SCHEMA_VERSION,
  CANDIDATE_STATUSES,
  candidateManifestSha256,
  canonicalCandidateManifestJson,
  validateCandidateManifest,
} from './candidate-manifest.js';
export { StudioError, asStudioError, invariant } from './errors.js';
